import { LayoutModule } from '@angular/cdk/layout';
import { NgModule } from '@angular/core';

import {
  MatDatepickerModule,
  MatInputModule,
  MatNativeDateModule,
  MatSelectModule,
  MatButtonModule,
  MatToolbarModule,
  MatProgressBarModule,
  MatTableModule,
  MatTabsModule,
  MatSidenavModule,
  MatIconModule,
  MatDialogModule,
  MatListModule,
  MatSlideToggleModule,
  MatCardModule,
  MatChipsModule,
  MatExpansionModule,
  MatProgressSpinnerModule,
  MatMenuModule,
  MatSnackBarModule,
  MatPaginatorModule,
  MatTooltipModule,
  MatCheckboxModule,
  MatRippleModule,
  MatGridListModule,
} from '@angular/material';

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

@NgModule({
  declarations: [
  ],
  imports: [
    BrowserAnimationsModule,
    MatDatepickerModule,
    MatInputModule,
    MatNativeDateModule,
    MatSelectModule,
    MatButtonModule,
    MatToolbarModule,
    MatProgressBarModule,
    MatTableModule,
    MatTabsModule,
    MatSidenavModule,
    MatIconModule,
    MatDialogModule,
    MatListModule,
    MatSlideToggleModule,
    MatCardModule,
    MatChipsModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatMenuModule,
    MatSnackBarModule,
    MatPaginatorModule,
    MatTooltipModule,
    MatCheckboxModule,
    MatRippleModule,
    LayoutModule,
    MatGridListModule
  ],
  exports: [
    BrowserAnimationsModule,
    MatDatepickerModule,
    MatInputModule,
    MatNativeDateModule,
    MatSelectModule,
    MatButtonModule,
    MatToolbarModule,
    MatProgressBarModule,
    MatTableModule,
    MatTabsModule,
    MatSidenavModule,
    MatIconModule,
    MatDialogModule,
    MatListModule,
    MatSlideToggleModule,
    MatCardModule,
    MatChipsModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatMenuModule,
    MatSnackBarModule,
    MatPaginatorModule,
    MatTooltipModule,
    MatCheckboxModule,
    MatRippleModule,
    LayoutModule,
    MatGridListModule
  ]
})
export class MaterialModule { }
